### ISSUE TITLE
dpdk socket memory doesn't address NIC which is only on numa node 1 

### ISSUE THREAD

**Issue by Opiekelly** [oVirt/ovirt-ansible-dpdk-setup#4]
In set ovs facts module the section below needs to address if the numa node is node 1.

def get_socket_mem(nics_numa_info):
    socket_mem_list = []
    numa_nodes = list(nics_numa_info.keys())
    if len(numa_nodes) == 1:
        return '1024'
    return ','.join(['1024' for _ in range(numa_nodes)])

if there is only one numa node and its on node 1 then the return should be '0,1024'
Also shouldn't the pagesize be accounted for in this function?

**Comment by sandrobonazzola** [comment]
@igoihman can you please follow up?

**Comment by igoihman** [comment]
@sandrobonazzola I'm not an active developer in the oVirt team anymore, please tag someone from the team

**Comment by sandrobonazzola** [comment]
@michalskrivanek ?

**Comment by michalskrivanek** [comment]
This oVirt subproject is not actively developed anymore. Feel free to reopen if you want to take up this issue
